name: StartupYnot
favicon: null
layout_spectrum: 0.87997
typography_spectrum: 0
title: StartuPYnoT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#a1a1a1'
    - '#616161'
    - '#c7c7c7'
    - '#eaeaea'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.3187407171353698
  rhythmicContrast: 0.25
purpose: []
