name: StartupYnot
favicon: null
layout_spectrum: 0.15253
typography_spectrum: 0.78249
title: StartuPYnoT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#2e2721'
    - '#fefefc'
    - '#8a684c'
    - '#bd9369'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.3187407171353698
  rhythmicContrast: 0
purpose: []
