name: StartupYnot
favicon: null
layout_spectrum: 0.92329
typography_spectrum: 0.25542
title: StartuPYnoT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#49314b'
    - '#fefefe'
    - '#ba92ac'
    - '#cb6e43'
  brandStrength: 0.6875
  lightness: 0.9375
  saturation: 0.3187407171353698
  rhythmicContrast: 0
purpose: []
