name: StartupYnot
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: "StartuPYnoT - LeT's  gEt sTartEd"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#1b1b1d'
    - '#343537'
    - '#8c8c8c'
    - '#636466'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
